# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeDuYingYuan' do
  pod 'SVProgressHUD'
 pod 'MBProgressHUD' 
pod 'MJExtension'
pod 'AFNetworking'
pod 'SDWebImage' 


end
